### ISSUE TITLE
Failed to compile under OSX 10.11

### ISSUE THREAD

**Issue by joneslee85** [da4nik/geoip2#20]
OS: 10.11
Libs: libmaxminddb (1.0.4) (from Homebrew)

Steps to reproduce:
* Run `gem install maxmind_geoip2 -v '0.0.8' -- --with-opt-include=/usr/local/include`
* Got errors, following is the output of `mkmf.log`:

```
/Users/tle/.rbenv/versions/2.2.2/bin/ruby -r ./siteconf20150626-96182-1rhbaha.rb extconf.rb --with-opt-include=/usr/local/include/
checking for maxminddb.h... yes
checking for main() in -lmaxminddb... no
you must have mmdb library
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/Users/tle/.rbenv/versions/2.2.2/bin/$(RUBY_BASE_NAME)
	--with-maxminddblib
	--without-maxminddblib

extconf failed, exit code 1
```

Happy to pair with anyone who are willing to resolve this issue.

**Comment by filiptepper** [comment]
Same here.

**Comment by filiptepper** [comment]
Just compiled.

First, make sure you have Xcode 7 installed. Once you do run:

```bash
xcode-select --install
```

Compiled, seems to be working.

**Comment by joneslee85** [comment]
I still have this same problem :( - closed for now, will open if I could find any answer

**Comment by dtbaker** [comment]
For future me: this worked on mac

`ARCHFLAGS="-arch x86_64" bundle install`

and on linux I had to install mmdb first:

https://gist.github.com/leonardteo/9a128bc8ca983fa728aa08d8209e714a
